export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const SAVE_TIME = 'SAVE_TIME';
export const INITIALIZE_ACTIVITIES = 'INITIALIZE_ACTIVITIES';
export const SET_DAY_TIMER_DURATION = 'SET_DAY_TIMER_DURATION';